project:
    name: 'starter'
    type: 'bottle_mongo'
    db: 'starter'

server:
    hosts: ['root@96.126.102.11']
    type: 'nginx_uwsgi'

repository:
    path: '/var/www/starter.git'

production:
    path: '/var/www/starter'
    update: 'git'
    uwsgi:
        socket: 3100
    nginx:
        host: 'starter.datafly.net'

staging:
    path: '/var/www/starter_staging'
    update: 'git'
    uwsgi:
        socket: 3101
    nginx:
        host: 'staging.starter.datafly.net'