---
- hosts: datafly
  sudo: yes
  gather_facts: no
  connection: ssh
  tasks:
      - action: apt pkg=$item
        with_items:
          - python-pip
          - build-essential
          - python-dev
      - action: pip name=$item
        with_items:
          - pyzmq
          - pyasn1
          - PyCrypto
          - python-keyczar