---
- hosts: datafly-all
  connection: ssh
  user: root
  gather_facts: no
  tasks:
      - action: apt pkg=$item
        with_items:
          - python-pip
          - build-essential
          - python-dev
      - action: pip name=$item
        with_items:
          - pyzmq
          - pyasn1
          - PyCrypto
          - python-keyczar